version: '3'
services:
  exercise1:
    build: .
    ports:
        - "9001:9001"
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'